### PR TITLE
ESBMC updated && CPAchecker removed 

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by lucasccordeiro — CHANGES_REQUESTED** [review]
@omaralhawi: May I ask you to cleanup/improve the commit messages?

**Comment by lucasccordeiro** [comment]
For example, there are several commits related to "updated". What does it mean? Please take a look at those commits that contain repeated messages.

**Comment by ghost** [comment]
Hi Lucas, 
Please note that the (updated) commits are previous modification that is no longer exists because I overwrite them (it can be confirmed from here: https://github.com/omaralhawi/depthk), the new PR shows all the modification I made on my repostiroy. 

This PR request, is similar to the last version uploaded to SV-Comp

**Comment by lucasccordeiro** [comment]
Can you please squash those commits that contain repeated messages?

**Pull request closed without merging**
